강사님 강의 include, varable Routing/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path('index/', views.index, name='index'),
    # articles/{이름}/{숫자}
    path('catch/<str:name>/<int:number>/', views.catch, name='catch'),
]

강사님 강의 include, varable Routing/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

강사님 강의 include, varable Routing/articles/models.py
from django.db import models

# Create your models here.

강사님 강의 include, varable Routing/articles/views.py
from django.shortcuts import render

def index(request):

    context = {
        'click': 'click'
    }

    return render(request, 'articles/index.html', context)

def catch(request, name, number):
    # url에서 변수로 들어오는 값을 구분해서 사용하기 위해 받아와야한다
    context = {
        'name': name,
        'number': number,
    }
    return render(request, 'articles/catch.html', context)

# Create your views here.

강사님 강의 include, varable Routing/articles/templates/articles/catch.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>여기가 CATCH! 화면</h1>
        <h3>이름 : {{ name }}</h3>
        <h3>나이 : {{ number }}</h3>
    </div>
{% endblock content %}

강사님 강의 include, varable Routing/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>여기가 INDEX!</h1>
    <a href=" {% url 'articles:catch' '이귀현' 100 %}">누르면 이동한다잇</a>
</div>
{% endblock content %}

강사님 강의 include, varable Routing/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    {% block content %}
    
    {% endblock content %}
</body>
</html>